//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSniper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon msniper {
            get {
                object obj = ResourceManager.GetObject("msniper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSniper -register.
        /// </summary>
        internal static string registerProtocol {
            get {
                return ResourceManager.GetString("registerProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSniper -remove.
        /// </summary>
        internal static string removeProtocol {
            get {
                return ResourceManager.GetString("removeProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSniper -resetallsnipelist.
        /// </summary>
        internal static string resetSnipeList {
            get {
                return ResourceManager.GetString("resetSnipeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ൻ ∠牔湡汳瑡潩卮牴湩獧㨢嬠਍††ൻ ††∠敋≹›琢瑩敬Ⱒ਍†††嘢污敵㨢∠筛細瘠ㅻ嵽†‭戠⁹㉻≽਍††ⱽ਍††ൻ ††∠敋≹›搢獥牣灩楴湯Ⱒ਍†††嘢污敵㨢∠ほ⁽‭ㅻ⁽慍畮污倠歯浥湯匠楮数⁲‭祢笠紲ഢ †素ബ †笠਍†††䬢祥㨢∠楧䡴扵牐橯捥≴ബ ††∠慖畬≥›䜢瑩畈⁢牐橯捥⁴ほ≽਍††ⱽ਍††ൻ ††∠敋≹›挢牵敲瑮敖獲潩≮ബ ††∠慖畬≥›䌢牵敲瑮嘠牥楳湯›ほ≽਍††ⱽ਍††ൻ ††∠敋≹›瀢潲潴潣乬瑯潆湵≤ബ ††∠慖畬≥›倢潲潴潣⁬潮⁴潦湵⁤‭汐慥敳爠湵漠据⁥ほ≽਍††ⱽ਍††ൻ ††∠敋≹›猢畨摴睯䵮杳Ⱒ਍†††嘢污敵㨢∠牐杯慲⁭獩挠潬楳杮椠⁮ほ⁽敳潣摮≳਍††ⱽ਍††ൻ ††∠敋≹›氢瑡獥噴牥楳湯Ⱒ਍†††嘢污敵㨢∠慌整瑳嘠牥楳湯ഢ †素ബ †笠਍†††䬢祥㨢∠敮噷牥楳湯Ⱒ਍†††嘢污敵㨢∠䕎⁗䕖卒佉≎਍††ⱽ਍††ൻ ††∠敋≹›搢睯汮慯䱤湩≫ബ ††∠慖畬≥›䐢坏䱎䅏⁄䥌䭎ഢ †素ബ †笠਍†††䬢祥㨢∠畡潴潄湷潬摡獍≧ബ ††∠慖畬≥›倢䕒卓✠❄吠⁏啁佔䅍䥔⁃佄乗佌䑁丠坅嘠剅䥓乏传⁒剐卅⁓乁⁙䕋⁙但⁒塅呉⸮ഢ †素ബ †笠਍†††䬢祥㨢∠慷湲湩≧ബ ††∠慖畬≥›圢剁䥎䝎ഢ †素ബ †笠਍ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_en {
            get {
                return ResourceManager.GetString("translation_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - {1} Manuel Pokemon Avcı - by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;GitHub Projesi {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;Şuanki Versiyon: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protokol bulunamadı - Lütfen bir kere {0} &apos;yi çalıştırın&quot;
        ///    },
        ///    {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_tr {
            get {
                return ResourceManager.GetString("translation_tr", resourceCulture);
            }
        }
    }
}
