//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSniper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon msniper {
            get {
                object obj = ResourceManager.GetObject("msniper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start MSniper -register.
        /// </summary>
        internal static string registerProtocol {
            get {
                return ResourceManager.GetString("registerProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start MSniper -remove.
        /// </summary>
        internal static string removeProtocol {
            get {
                return ResourceManager.GetString("removeProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start MSniper -resetallsnipelist.
        /// </summary>
        internal static string resetSnipeList {
            get {
                return ResourceManager.GetString("resetSnipeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - v{1} Manual Pokemon Sniper - by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;Github Project {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;Current Version: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protocol not found - Please run once {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_en_US {
            get {
                return ResourceManager.GetString("translation_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  Por {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - v{1} Sniper Manual Pokemon - Por {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;GitHub Project {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;Version Actual: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protocolo no encontrado - Porfavor, inicie el protocolo una vez {0}&quot;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_es_ES {
            get {
                return ResourceManager.GetString("translation_es_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - v{1} Pokemon Sniper Manuale - by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;Progetto GitHub {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;Versione corrente: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protocollo non trovato - Perfavore esegui per una volta {0}&quot;
        ///    },
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_it_IT {
            get {
                return ResourceManager.GetString("translation_it_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - v{1} Manuel Pokemon Avcı - by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;GitHub Projesi {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;Şuanki Versiyon: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protokol bulunamadı - Lütfen bir kere {0} &apos;yi çalıştırın&quot;
        ///    },
        ///    {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_tr_TR {
            get {
                return ResourceManager.GetString("translation_tr_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - v{1} 手動狙擊器 - by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;GitHub 專案連結 {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;目前版本: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protocol 未被找到 - 請先執行一次 {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;shutdownMsg&quot;,
        ///      &quot;Value&quot;: &quot;程序將關閉於 {0} 秒&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_zh_TW {
            get {
                return ResourceManager.GetString("translation_zh_TW", resourceCulture);
            }
        }
    }
}
