//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSniper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSniper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon msniper {
            get {
                object obj = ResourceManager.GetObject("msniper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSniper -register.
        /// </summary>
        internal static string registerProtocol {
            get {
                return ResourceManager.GetString("registerProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSniper -remove.
        /// </summary>
        internal static string removeProtocol {
            get {
                return ResourceManager.GetString("removeProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSniper -resetallsnipelist.
        /// </summary>
        internal static string resetSnipeList {
            get {
                return ResourceManager.GetString("resetSnipeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - {1} Manual Pokemon Sniper - by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;GitHub Project {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;Current Version: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protocol not found - Please run once {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;shu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_en {
            get {
                return ResourceManager.GetString("translation_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ൻ ∠牔湡汳瑡潩卮牴湩獧㨢嬠਍††ൻ ††∠敋≹›琢瑩敬Ⱒ਍†††嘢污敵㨢∠筛細瘠ㅻ嵽†‭倠牯笠紲ഢ †素ബ †笠਍†††䬢祥㨢∠敤捳楲瑰潩≮ബ ††∠慖畬≥›笢細ⴠ笠紱匠楮数⁲慍畮污倠歯浥湯ⴠ倠牯笠紲ഢ †素ബ †笠਍†††䬢祥㨢∠楧䡴扵牐橯捥≴ബ ††∠慖畬≥›䜢瑩畈⁢牐橯捥⁴ほ≽਍††ⱽ਍††ൻ ††∠敋≹›挢牵敲瑮敖獲潩≮ബ ††∠慖畬≥›嘢牥楳湯䄠瑣慵㩬笠細ഢ †素ബ †笠਍†††䬢祥㨢∠牰瑯捯汯潎䙴畯摮Ⱒ਍†††嘢污敵㨢∠牐瑯捯汯⁯潮攠据湯牴摡⁯‭潐晲癡牯‬湩捩敩攠⁬牰瑯捯汯⁯湵⁡敶⁺ほ≽਍††ⱽ਍††ൻ ††∠敋≹›猢畨摴睯䵮杳Ⱒ਍†††嘢污敵㨢∠汅瀠潲牧浡⁡敳挠牥慲慲攠⁮ほ⁽敳畧摮獯ഢ †素ബ †笠਍†††䬢祥㨢∠慬整瑳敖獲潩≮ബ ††∠慖畬≥›唢瑬浩⁡敖獲潩≮਍††ⱽ਍††ൻ ††∠敋≹›渢睥敖獲潩≮ബ ††∠慖畬≥›丢䕕䅖嘠剅䥓乏ഢ †素ബ †笠਍†††䬢祥㨢∠潤湷潬摡楌歮Ⱒ਍†††嘢污敵㨢∠久䅌䕃䐠⁅䕄䍓剁䅇ഢ †素ബ †笠਍†††䬢祥㨢∠畡潴潄湷潬摡獍≧ബ ††∠慖畬≥›倢䕒䥓乏⁅䐧‧䅐䅒䄠呕䑏卅䅃䝒剁䰠⁁䍁啔䱁婉䍁佉⹎传䌠䅕兌䥕剅传剔⁁䕔䱃⁁䅐䅒匠䱁剉⸮ഢ †素ബ †笠਍†††䬢祥㨢 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_es {
            get {
                return ResourceManager.GetString("translation_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TranslationStrings&quot;: [
        ///    {
        ///      &quot;Key&quot;: &quot;title&quot;,
        ///      &quot;Value&quot;: &quot;[{0} v{1}]  -  by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;description&quot;,
        ///      &quot;Value&quot;: &quot;{0} - {1} Manuel Pokemon Avcı - by {2}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;gitHubProject&quot;,
        ///      &quot;Value&quot;: &quot;GitHub Projesi {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;currentVersion&quot;,
        ///      &quot;Value&quot;: &quot;Şuanki Versiyon: {0}&quot;
        ///    },
        ///    {
        ///      &quot;Key&quot;: &quot;protocolNotFound&quot;,
        ///      &quot;Value&quot;: &quot;Protokol bulunamadı - Lütfen bir kere {0} &apos;yi çalıştırın&quot;
        ///    },
        ///    {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string translation_tr {
            get {
                return ResourceManager.GetString("translation_tr", resourceCulture);
            }
        }
    }
}
